### ISSUE TITLE
Login page validation

### ISSUE THREAD

**Issue by mrunmayee9601** [QAZIMAAZARSHAD/Apni-Dukaan#124]
## Describe the bug
On Sign Up page in Name fields ,numbers are also getting accepted. I would like to build a solution where there will be alerts for wrong input in Name fields. 
@QAZIMAAZARSHAD Pls assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
@mrunmayee9601 issue name should be short and descriptive.

**Comment by mrunmayee9601** [comment]
> @mrunmayee9601 issue name should be short and descriptive.

Okay understood

**Comment by satyampgt4** [comment]
@mrunmayee9601  any updates.........?

**Comment by mayuribotre15** [comment]
I want to apply for login page validation.
I have done a similar project, check here:
https://mayuribotre15.github.io/validation-form.github.io/

**Comment by QAZIMAAZARSHAD** [comment]
@mayuribotre15 sign-up is already fine.

The login page can be improved.

But don't do like you have shown in that link. Generate a sweet alert for every warning and submission.

**Comment by QAZIMAAZARSHAD** [comment]
@mayuribotre15 I will assign you this issue once you resolve the other assigned issue.

**Comment by Riya123-code** [comment]
can i work on login page validation?

**Comment by QAZIMAAZARSHAD** [comment]
Re: Can you please let me know what all validations Are to be added other than on the signUp page username field? 

@Riya123-code 

- Correct emails should be accepted in the mail field, like xyz@gmail.com or xyz@co.com. But entries like h6@g.ccccc are also getting accepted.
- And the password requires only 6 characters right now, add a few more constraints like the range should be 6-18 characters, at least 1 capital letter, at least 1 small letter, at least 1 special character, etc.
- Also, every time user makes a wrong entry all inputs vanish due to refresh, this should not happen.
- Also, a specific warning pop-up should appear for wrong entries like a special character is missing in the password or @fwwfff.kj is not the correct email format, etc.
- Forgot password hyperlink should redirect to forgot password page.

Do the required changes in the login.html page only for now.
